[2025-04-18 04:05:26,042][__main__][INFO] - Instantiating trainer: src.trainers.sae_trainer.SAETrainer
[2025-04-18 04:05:26,047][__main__][ERROR] - An error occurred during trainer instantiation or execution:
Traceback (most recent call last):
  File "/home/ozanbayiz/miniforge3/envs/irve/lib/python3.13/site-packages/hydra/_internal/utils.py", line 635, in _locate
    obj = import_module(part0)
  File "/home/ozanbayiz/miniforge3/envs/irve/lib/python3.13/importlib/__init__.py", line 88, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1324, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'src'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/ozanbayiz/miniforge3/envs/irve/lib/python3.13/site-packages/hydra/_internal/instantiate/_instantiate2.py", line 134, in _resolve_target
    target = _locate(target)
  File "/home/ozanbayiz/miniforge3/envs/irve/lib/python3.13/site-packages/hydra/_internal/utils.py", line 637, in _locate
    raise ImportError(
    ...<2 lines>...
    ) from exc_import
ImportError: Error loading 'src.trainers.sae_trainer.SAETrainer':
ModuleNotFoundError("No module named 'src'")
Are you sure that module 'src' is installed?

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/ozanbayiz/irve/src/main.py", line 39, in main
    trainer = hydra.utils.instantiate(cfg.trainer, cfg=cfg, _recursive_=False)
  File "/home/ozanbayiz/miniforge3/envs/irve/lib/python3.13/site-packages/hydra/_internal/instantiate/_instantiate2.py", line 226, in instantiate
    return instantiate_node(
        config, *args, recursive=_recursive_, convert=_convert_, partial=_partial_
    )
  File "/home/ozanbayiz/miniforge3/envs/irve/lib/python3.13/site-packages/hydra/_internal/instantiate/_instantiate2.py", line 333, in instantiate_node
    _target_ = _resolve_target(node.get(_Keys.TARGET), full_key)
  File "/home/ozanbayiz/miniforge3/envs/irve/lib/python3.13/site-packages/hydra/_internal/instantiate/_instantiate2.py", line 139, in _resolve_target
    raise InstantiationException(msg) from e
hydra.errors.InstantiationException: Error locating target 'src.trainers.sae_trainer.SAETrainer', set env var HYDRA_FULL_ERROR=1 to see chained exception.
full_key: trainer
